import { Geist } from "next/font/google";

import "../styles/globals.css";
import "../styles/reset.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={`${geistSans.variable}`}>
        {children}
      </body>
    </html>
  );
}
